<#
.SYNOPSIS
  Generates ModuleIndex.md from public source scripts (function name, path, synopsis).
.DESCRIPTION
  Scans Source/Public for .ps1 files, extracts the function name and .SYNOPSIS,
  and writes a Markdown index to the output path and repo root. Used by Start-ModuleBuild.ps1.
#>
function Export-ModuleIndex {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)]
    [string]$SourcePath,
    [Parameter(Mandatory)]
    [string]$OutputPath,
    [Parameter(Mandatory)]
    [string]$RepoRoot
  )
  $publicPath = Join-Path $SourcePath "Public"
  $indexEntries = [System.Collections.ArrayList]::new()
  foreach ($file in (Get-ChildItem -Path $publicPath -Recurse -Filter "*.ps1")) {
    $relativePath = $file.FullName.Substring($SourcePath.Length).TrimStart([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $content = Get-Content -Path $file.FullName -Raw
    $funcMatch = [regex]::Match($content, 'function\s+([A-Za-z0-9\-]+)\s*\{')
    if (-not $funcMatch.Success) { continue }
    $funcName = $funcMatch.Groups[1].Value
    $synopsis = ''
    $synopsisMatch = [regex]::Match($content, '\.SYNOPSIS\s*\r?\n\s*(.+?)(?=\r?\n\s*\.|\r?\n\s*#>|\r?\n\r?\n|\z)', [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if ($synopsisMatch.Success) {
      $synopsis = ($synopsisMatch.Groups[1].Value -replace '\s+', ' ').Trim()
    }
    [void]$indexEntries.Add([PSCustomObject]@{ Function = $funcName; Path = $relativePath; Synopsis = $synopsis })
  }
  $indexMd = @"
# PS-Okta module index

Generated by Start-ModuleBuild.ps1. Use this file to find the source script for a function without reading the full codebase.

| Function | Path | Synopsis |
|----------|------|----------|
"@
  foreach ($e in ($indexEntries | Sort-Object Function)) {
    $synopsisEscaped = ($e.Synopsis -replace '\|', '&#124;') -replace "`r?`n", ' '
    $indexMd += "`n| $($e.Function) | $($e.Path) | $synopsisEscaped |"
  }
  $indexMd += "`n"
  $indexPathOutput = Join-Path $OutputPath "ModuleIndex.md"
  $indexPathRoot = Join-Path $RepoRoot "ModuleIndex.md"
  Set-Content -Path $indexPathOutput -Value $indexMd -Encoding UTF8
  Set-Content -Path $indexPathRoot -Value $indexMd -Encoding UTF8
  Write-Host "  ModuleIndex.md written to output and repo root."
}
